name: Auto-label new issues

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Format labels
        run: echo "LABELS=$(echo '${{ vars.ISSUE_LABELS }}' | tr -d '\r' | tr ',' '\n' | sed 's/^ *//g' | sed 's/ *$//g' | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_ENV

      - name: Add labels to new issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.LABELS }}
