name: Auto-label new issues

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Read labels from file
        run: |
          LABELS=$(cat .github/labels.json | jq -r '.labels | join(",")')
          echo "LABELS=$LABELS" >> $GITHUB_ENV  # Set LABELS to the list from the file

      - name: Debug - Print formatted LABELS
        run: echo "Formatted LABELS=${{ env.LABELS }}"  # Print the formatted labels

      - name: Add labels to new issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.LABELS }}
