name: Auto-label new issues

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    env:
      ISSUE_LABELS: ${{ secrets.ISSUE_LABELS }}  # Reference the secret as an environment variable

    steps:
      - name: Format labels
        run: |
          LABELS=$(echo "${{ env.ISSUE_LABELS }}" | tr -d '\r' | tr ',' '\n' | sed 's/^ *//g' | sed 's/ *$//g' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "LABELS=$LABELS" >> $GITHUB_ENV

      - name: Add labels to new issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.LABELS }}
