name: Auto-label new issues

on:
  issues:
    types: [opened]

jobs:
  label:
    name: Add labels to new issue
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get labels from labels.json
        id: get-labels
        run: |
          if [ ! -f .github/labels.json ]; then
            echo "Error: .github/labels.json file not found"
            exit 1
          fi
          
          LABELS=$(cat .github/labels.json | jq -r '.labels | join(",")')
          echo "labels=$LABELS" >> $GITHUB_OUTPUT
      
      - name: Add labels to new issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.get-labels.outputs.labels }}