name: Auto-label new issues

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      # Step 1: Checkout the repository (using the correct token for private repos)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure GITHUB_TOKEN has repo read/write permissions

      # Step 2: Ensure labels.json file exists and read it
      - name: Get labels from labels.json
        run: |
          if [ ! -f .github/labels.json ]; then
            echo ".github/labels.json file not found."
            exit 1
          fi
          LABELS=$(cat .github/labels.json | jq -r '.labels | join(",")')
          echo "Formatted LABELS=$LABELS"  # To see the result in logs
          echo "LABELS=$LABELS" >> $GITHUB_ENV

      # Step 3: Add labels to the new issue
      - name: Add labels to new issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the same token for adding labels
          labels: ${{ env.LABELS }}

