name: Auto-label new issues

on:
  issues:
    types: [opened]

jobs:
  label:
    name: Add labels to new issue
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add labels to new issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          if [ ! -f .github/labels.json ]; then
            echo "Error: .github/labels.json file not found"
            exit 1
          fi
          
          # Read labels from JSON and add them one by one
          for label in $(cat .github/labels.json | jq -r '.labels[]'); do
            echo "Adding label: $label"
            gh issue edit $ISSUE_NUMBER --add-label "$label"
          done