name: Notify Stale PRs
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch open PRs
        id: fetch-prs
        run: |
          PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")
          echo "::set-output name=prs::$PRS"
      - name: Notify stale PRs
        run: |
          echo "${{ steps.fetch-prs.outputs.prs }}" | jq -c '.[]' | while read pr; do
            created_at=$(echo "$pr" | jq -r '.created_at')
            pr_id=$(echo "$pr" | jq -r '.number')
            creator=$(echo "$pr" | jq -r '.user.login')
            age=$(( ($(date +%s) - $(date -d "$created_at" +%s)) / 86400 ))
            if [ "$age" -gt 0 ]; then
              curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/issues/$pr_id/comments" \
                -d '{"body": "This PR has been open for more than 3 days. Please provide a reason for the delay."}'
            fi
          done